name: game_achievement_analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - psycopg2
  - faker
  - matplotlib
  - dash
  - streamlit
  - pip
  - pip:
      - -e .  # Install the package from setup.py (editable mode)
variables:
  DATA_DIR: "Data"
  DB_HOST: "localhost"
  DB_NAME: "your-db-name"
  DB_USER: "your-username"
  DB_PASS: "your-password"
  PLAYERS_FILE: "players.csv"
  GAMES_FILE: "games.csv"
  ACHIEVEMENTS_FILE: "achievements.csv"
  TIME_FILE: "time.csv"
  ACHIEVEMENT_FACTS_FILE: "achievement_facts.csv"